language: python
matrix:
  include:
    - python: 2.7
      env:
        - TOXENV=django19-py27
        - TOXENV=django110-py27
        - TOXENV=django111-py27
    - python: 3.6
      env:
       - TOXENV=django19-py36
       - TOXENV=django110-py36
       - TOXENV=django111-py36
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls