language: python
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
env:
  - TOXENV=django18-py27
  - TOXENV=django18-py35
  - TOXENV=django19-py27
  - TOXENV=django19-py35
  - TOXENV=django110-py27
  - TOXENV=django110-py35
  - TOXENV=django111-py27
  - TOXENV=django111-py35
after_success:
  - coveralls